version: 0.0
os: linux

files:
  - source: /
    destination: /home/ubuntu/initializer-server

permissions:
  - object: scripts/start-server.sh
    owner: ubuntu
    group: ubuntu
    mode: 755

hooks:
  ApplicationStart:
    - location: scripts/start-server.sh
      timeout: 60
      runas: ubuntu